// Refresh the precache block in src/sw.js: the list of every file under src/ and a
// VERSION hashed from their contents. Run it before each release (`npm run precache`);
// test/precache.test.js fails while the block is out of date.
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = fileURLToPath(new URL('../src/', import.meta.url));
const SW = join(SRC, 'sw.js');
const START = '// precache:start', END = '// precache:end';

/** Every file under src/ except the service worker and dotfiles, as sorted POSIX paths. */
async function assets(dir = SRC) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.')) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...await assets(p));
    else if (p !== SW) out.push(relative(SRC, p).split(sep).join('/'));
  }
  return out.sort();
}

/** The precache block as it should read for the files currently in src/. */
export async function expectedBlock() {
  const files = await assets(), hash = createHash('sha256');
  for (const f of files) hash.update(f).update('\0').update(await readFile(join(SRC, f))).update('\0');
  return [
    `${START} (generated by tools/precache.mjs; do not edit by hand)`,
    `const VERSION = '${hash.digest('hex').slice(0, 12)}';`,
    'const ASSETS = [',
    ...files.map(f => `  '${f}',`),
    '];',
    END,
  ].join('\n');
}

/** src/sw.js split around its precache block. */
export async function readServiceWorker() {
  const text = await readFile(SW, 'utf8');
  const a = text.indexOf(START), b = text.indexOf(END);
  if (a < 0 || b < a || text.indexOf(START, a + 1) >= 0)
    throw new Error(`src/sw.js needs exactly one "${START}" ... "${END}" block`);
  return { before: text.slice(0, a), block: text.slice(a, b + END.length), after: text.slice(b + END.length) };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const sw = await readServiceWorker(), block = await expectedBlock();
  if (sw.block === block) console.log('src/sw.js is up to date');
  else {
    await writeFile(SW, sw.before + block + sw.after);
    console.log(`src/sw.js: ${block.split('\n')[1]} (${block.split('\n').length - 5} files)`);
  }
}
