/* Tetranoid service worker: the whole game is precached, so it plays offline.
   `npm run precache` rewrites VERSION and ASSETS from the files in src/; a new
   VERSION is what makes browsers pick up a release. URLs are relative to this
   file, so the game works from any folder. */

// precache:start (generated by tools/precache.mjs; do not edit by hand)
const VERSION = 'fd0db9697689';
const ASSETS = [
  'css/base.css',
  'css/fonts.css',
  'css/hud.css',
  'css/pad.css',
  'css/stage.css',
  'css/veil.css',
  'fonts/bungee-latin-400.woff2',
  'fonts/bungee.OFL.txt',
  'fonts/saira-condensed-latin-400.woff2',
  'fonts/saira-condensed-latin-600.woff2',
  'fonts/saira-condensed-latin-700.woff2',
  'fonts/saira-condensed.OFL.txt',
  'icons/apple-touch-icon-180x180.png',
  'icons/favicon.ico',
  'icons/icon.svg',
  'icons/maskable-icon-512x512.png',
  'icons/og-image.png',
  'icons/pwa-192x192.png',
  'icons/pwa-512x512.png',
  'icons/pwa-64x64.png',
  'index.html',
  'js/config.js',
  'js/device.js',
  'js/events.js',
  'js/fx/audio.js',
  'js/fx/feedback.js',
  'js/fx/haptics.js',
  'js/game/ball.js',
  'js/game/board.js',
  'js/game/paddle.js',
  'js/game/piece.js',
  'js/game/run.js',
  'js/game/state.js',
  'js/input/controls.js',
  'js/input/keyboard.js',
  'js/input/touch.js',
  'js/main.js',
  'js/platform/pwa.js',
  'js/platform/wakelock.js',
  'js/render/materials.js',
  'js/render/particles.js',
  'js/render/scene.js',
  'js/render/three.js',
  'js/render/view.js',
  'js/ui/hud.js',
  'js/ui/screens.js',
  'js/util.js',
  'manifest.webmanifest',
  'vendor/three.LICENSE',
  'vendor/three.min.js',
];
// precache:end

const CACHE = 'tetranoid-' + VERSION;
// On localhost, go to the network first so that edits show up straight away.
const DEV = ['localhost', '127.0.0.1', '[::1]'].includes(self.location.hostname);

self.addEventListener('install', e => {
  // cache: 'reload' skips the HTTP cache, so a new version never stores stale files
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS.map(u => new Request(u, { cache: 'reload' })))));
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('tetranoid-') && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

// A new version waits until the player taps "Update" on the menu (see js/platform/pwa.js).
self.addEventListener('message', e => { if (e.data === 'skip-waiting') self.skipWaiting(); });

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(DEV ? networkFirst(req) : cacheFirst(req));
});

async function cached(req) {
  const cache = await caches.open(CACHE);
  return (await cache.match(req, { ignoreSearch: true }))
      || (req.mode === 'navigate' ? await cache.match('index.html') : undefined);
}
async function cacheFirst(req) {
  return (await cached(req)) || fetch(req);
}
async function networkFirst(req) {
  try { return await fetch(req); }
  catch (err) { const hit = await cached(req); if (hit) return hit; throw err; }
}
